apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-ui
spec:
  selector:
    matchLabels:
      app: vote-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: vote-ui
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: vote-ui
          image: quay.io/narendraprasadn/java:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

