apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:53e7c1ffe25956dac03c9bf3c1b71422e23d3ed17debec90e43b6c955cb1bd4b
  name: quay.io/narendraprasadn/java:dev
  newName: quay.io/narendraprasadn/java:10479b4b09a547bc67bcfa0ebc8d72cf6cef8901
- digest: sha256:6d743f627726e5725a226d6a39cfc2d719c8e242eab19e336bafb270d180b594
  name: quay.io/narendraprasadn/java:latest
  newName: quay.io/narendraprasadn/java:20febeb66fa1fcb95ee895a06686cf9a778db6b6
