apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:d800aa25c8b48c97d85d04a2fde63a1be38fbe4743cfa233314bdaf93c3b3a36
  name: quay.io/narendraprasadn/java:latest
  newName: quay.io/narendraprasadn/java
