apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:81c8419df4ae63759759ba9df7cdddd99db4124b32e0f90bc120191dece91a70
  name: quay.io/narendraprasadn/java:latest
  newName: quay.io/narendraprasadn/java:12a74878d6a1dd3f0d52ef58dc689a1850992c61
