apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:bbee83f3e9b65b02e3a81cc9f7a496b0ee30820cd23e3c9a52bbc81c12286256
  name: quay.io/narendraprasadn/java-cicd:dev
  newName: quay.io/narendraprasadn/java-cicd:preproduction
- digest: sha256:50e7d31e83948710280e12b04029f6c8e32cd0362b0012160d304f2a9ee38c12
  name: quay.io/narendraprasadn/java:dev
  newName: quay.io/narendraprasadn/java:test
- digest: sha256:88eda3ce2e8e8ee133b6513c5caddea7405b0a2bcb3b6549f735993b3a77b728
  name: quay.io/narendraprasadn/java:latest
  newName: quay.io/narendraprasadn/java:test
