apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:3891d0caeab7508f323466e82e7d8186690a1e357f5cbc73113e1fe290ebd960
  name: quay.io/narendraprasadn/java:latest
  newName: quay.io/narendraprasadn/java
