apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:88eda3ce2e8e8ee133b6513c5caddea7405b0a2bcb3b6549f735993b3a77b728
  name: quay.io/narendraprasadn/java
  newName: quay.io/narendraprasadn/java:faff8e53f85ea279dfc9a419019e0a0fbf334c16
- digest: sha256:05d2956b18e35ee377691ce400817db61adb8f907b74614cd48d3698053bb393
  name: quay.io/narendraprasadn/java:latest
  newName: quay.io/narendraprasadn/java
