apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:1e542a56a6c553dee8f1aae896af37d10c634976621b190d409d585c5b1790e5
  name: quay.io/narendraprasadn/java-cicd:dev
  newName: quay.io/narendraprasadn/java-cicd:test
- digest: sha256:50e7d31e83948710280e12b04029f6c8e32cd0362b0012160d304f2a9ee38c12
  name: quay.io/narendraprasadn/java:dev
  newName: quay.io/narendraprasadn/java:test
- digest: sha256:88eda3ce2e8e8ee133b6513c5caddea7405b0a2bcb3b6549f735993b3a77b728
  name: quay.io/narendraprasadn/java:latest
  newName: quay.io/narendraprasadn/java:test
