apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:c560cfe5bb58005a4164719f12730ed22cbd22d4cc8622b8c9cd0f369451a691
  name: quay.io/narendraprasadn/java:latest
  newName: quay.io/narendraprasadn/java
