apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:fedbaf27e25c1b0feb176f63e3a8ded1a6839a2ee56e416a956fa7d303f48385
  name: quay.io/narendraprasadn/java:latest
  newName: quay.io/narendraprasadn/java
