apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:a35b57611a001ca8669176d358c3a837ea3854e87d8c59a50bc6db4e13b4d047
  name: quay.io/narendraprasadn/java:latest
  newName: quay.io/narendraprasadn/java
