apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:2c396b94c1864191fe6222966365242df63ebb6aa6ad8b8ef675da0d30958e79
  name: quay.io/narendraprasadn/java:latest
  newName: quay.io/narendraprasadn/java
