apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:ab5611821919166b4edf552801bc7766414a9f07dae4919bbfa48a73b452afc3
  name: quay.io/narendraprasadn/java:dev
  newName: quay.io/narendraprasadn/java:test
- digest: sha256:88eda3ce2e8e8ee133b6513c5caddea7405b0a2bcb3b6549f735993b3a77b728
  name: quay.io/narendraprasadn/java:latest
  newName: quay.io/narendraprasadn/java:test
