apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: egress-serviceentry
spec:
  hosts:
  - www.vinothbalakrishna.tech
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
