apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: my-service-entry
spec:
  hosts:
    - www.vinothbalakrishna.tech
  ports:
    - number: 80
      name: http
      protocol: HTTP
  location: MESH_EXTERNAL
