apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#baseDir: ../../base
resources:
- ../../base
- deployment.yaml
- namespace.yaml

# Adding prefix as Dev
namePrefix: Dev-

# Namespace
namespace: argocd-narendra-dev
   
# common labels 
commonLabels:
 company: imss 
   project: narendraprasadn

# updating replicas
patches: 
 - target: 
     kind: Deployment 
     name: vote-ui
   patch: |-
    - op: replace 
      path: /spec/replicas
      value: 5
