apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#baseDir: ../../base
resources:
- ../../base

# Adding prefix as Dev
namePrefix: Dev-

# Namespace
namespace: dev
   
# common labels 
commonLabels:
 company: imss 
   project: narendraprasadn

# updating replicas
patches: 
 - target: 
     kind: Deployment 
       name: argocd-deployment
   patch: |-
    - op: replace 
      path: /spec/replicas
      value: 5
