apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
      version:v1
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        version:v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: backend
          image: mysql
          imagePullPolicy: Always
          ports:
           - containerPort: 8080
         env:
          - name: APP_BACKEND
            value: https://httpbin.org/status/200
          - name: APP_VERSION
            value: v1
          - name: quarkus.log.console.color
            value: 'false'
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - prot: 8080
      name: http
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      version:v1
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: frontend
          image: quay.io/narendraprasadn/java-cicd:dev
          imagePullPolicy: Always
          ports:
           - containerport: 8080
          env:
            - name: BACKEND_HOST
              value: backend
            - name: BACKEND_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - prot: 8080
      name: http
      targetPort: 8080
---
apiVersion: v1
kind: Route
metadata:
  name: frontend
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: frontend
    weight: 100
  wildcardPolicy: None
