apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: quay.io/narendraprasadn/java-cicd
          imagePullPolicy: Always
          ports:
           - containerport: 8080
          env:
            - name: BACKEND_HOST
              value: backend
            - name: BACKEND_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - prot: 8080
      name: http
      targetPort: 8080
---
apiVersion: v1
kind: Route
metadata:
  name: frontend
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: frontend
    weight: 100
  wildcardPolicy: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mysql
          imagePullPolicy: Always
          ports:
           - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - prot: 8080
      name: http
      targetPort: 8080
